# Generated by Django 6.0.2 on 2026-05-27 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0013_pdfresource_original_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfresource',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='kb_pdfs/'),
        ),
    ]
