# Generated by Django 6.0.2 on 2026-05-26 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0013_documentauthorinstitution_documenttype_and_more'),
        ('ask', '0013_pdfresource_original_filename'),
    ]

    operations = [
    ]
