# Generated by Django 6.0.2 on 2026-06-02 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0014_merge_20260526_2133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdfresource',
            name='date_published_precision',
        ),
        migrations.RemoveField(
            model_name='websiteresource',
            name='date_published_precision',
        ),
        migrations.AlterField(
            model_name='pdfresource',
            name='date_published',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='websiteresource',
            name='date_published',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
