# Generated by Django 6.0.2 on 2026-06-09 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0014_alter_pdfresource_file'),
        ('ask', '0015_remove_pdfresource_date_published_precision_and_more'),
    ]

    operations = [
    ]
