# Generated by Django 6.0.2 on 2026-06-17 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0016_merge_20260609_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfresource',
            name='publisher',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='websiteresource',
            name='publisher',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
