# Generated by Django 6.0.2 on 2026-10-08 18:40

import ask.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0017_pdfresource_publisher_websiteresource_publisher'),
    ]

    operations = [
        migrations.AddField(
            model_name='simworkflow',
            name='response_content_regex',
            field=models.CharField(blank=True, default='', help_text="Optional regex used to extract the JSON content from the agent's response (e.g. when it is wrapped in a markdown code block). If the regex has a capture group, the first group is used, otherwise the whole match. Leave blank to use the response as is.", max_length=500, validators=[ask.models.validate_regex]),
        ),
    ]
