# Generated by Django 6.0.2 on 2026-10-07 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0017_pdfresource_publisher_websiteresource_publisher'),
    ]

    operations = [
        migrations.CreateModel(
            name='DebugSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debug_mode', models.BooleanField(default=False, help_text='When enabled, raw responses from the AI are logged and viewable in the admin.')),
            ],
            options={
                'verbose_name': 'Debug Settings',
                'verbose_name_plural': 'Debug Settings',
            },
        ),
        migrations.CreateModel(
            name='LLMResponseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_response', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'LLM Response Log',
                'verbose_name_plural': 'LLM Response Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
